### ISSUE TITLE
LibreLists submitted to Free Software Directory

### ISSUE THREAD

**Issue by singerintherain** [AdrBog/LibreLists#2]
LibreLists is being looked at for inclusion in the Free Software Directory. It looks like free software, but the FSD requires the download link to point to a specific version. Do you think you could create a release that could be linked to?

**Comment by AdrBog** [comment]
Hi, I just created a release in the repository, here is the link:
https://github.com/AdrBog/LibreLists/releases/tag/v0.2.0

It's the first time i create a release but i think i made it right
I hope it will be useful
